"""Prepare the workspace's robosuite 1.4.0 installation for Windows.

Run with .runtime/remaining_libero/venv/Scripts/python.exe after pip finishes.
No network, package imports, upstream Python edits, or parent-environment writes
are performed. The added official macros_private hook configures module macros
before robosuite imports its binding/renderer and file logger.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
from pathlib import Path
import platform
import shutil


ROOT = Path(__file__).resolve().parents[1]
RUNTIME = ROOT / ".runtime" / "remaining_libero"
MACROS = '''"""Generated by remaining-goals Windows preparation; see windows_compat.json."""
# robosuite 1.4.0 imports this hook from __init__, but macros.py does not import
# it back. Set the actual module fields read by binding_utils and log_utils.
import robosuite.macros as _remaining_macros
_remaining_macros.MUJOCO_GPU_RENDERING = False
_remaining_macros.FILE_LOGGING_LEVEL = None
MUJOCO_GPU_RENDERING = False
FILE_LOGGING_LEVEL = None
'''


def _hash(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _contained(path, root):
    path, root = Path(path).resolve(), Path(root).resolve()
    if not path.is_relative_to(root):
        raise ValueError(f"package path is outside the workspace venv: {path}")
    return path


def prepare_windows(runtime: Path = RUNTIME) -> dict:
    """Add a same-version DLL and a recorded private macro configuration."""
    if platform.system() != "Windows":
        raise RuntimeError("Windows preparation must run on Windows")
    runtime = Path(runtime).resolve()
    venv = runtime / "venv"
    if not venv.is_dir():
        raise ValueError("workspace venv must already exist")
    distributions = {name: importlib.metadata.distribution(name) for name in ("robosuite", "mujoco")}
    for name, expected in (("robosuite", "1.4.0"), ("mujoco", "2.3.7")):
        if distributions[name].version != expected:
            raise ValueError(f"Windows compatibility is reviewed for {name}=={expected} only")
    packages = {name: _contained(dist.locate_file(name), venv) for name, dist in distributions.items()}
    robosuite_dir, mujoco_dir = packages["robosuite"], packages["mujoco"]
    binding = (robosuite_dir / "utils" / "binding_utils.py").read_text(encoding="utf-8")
    init = (robosuite_dir / "__init__.py").read_text(encoding="utf-8")
    if "ctypes.WinDLL" not in binding or '"mujoco.dll"' not in binding:
        raise ValueError("unexpected robosuite Windows DLL loader; compatibility needs review")
    if "from robosuite.macros_private import *" not in init:
        raise ValueError("robosuite official private macro entry point is unavailable")
    sources = [path for path in mujoco_dir.rglob("*") if path.is_file() and path.name.casefold() == "mujoco.dll"]
    if len(sources) != 1:
        raise ValueError(f"expected exactly one DLL from mujoco==2.3.7, found {len(sources)}")
    source = _contained(sources[0], venv)
    if source.read_bytes()[:2] != b"MZ":
        raise ValueError("installed MuJoCo DLL is not a Windows PE binary")
    target = _contained(robosuite_dir / "utils" / "mujoco.dll", venv)
    macro_path = _contained(robosuite_dir / "macros_private.py", venv)
    macro_bytes = MACROS.encode("utf-8")
    # Preflight every possible overwrite before changing any package file.
    if target.exists() and _hash(target) != _hash(source):
        raise ValueError("robosuite already has a different MuJoCo DLL; refusing to overwrite it")
    if macro_path.exists() and macro_path.read_bytes() != macro_bytes:
        raise ValueError("robosuite already has a foreign macros_private.py; refusing to overwrite it")
    if not target.exists():
        shutil.copyfile(source, target)
    if not macro_path.exists():
        macro_path.write_bytes(macro_bytes)
    if _hash(source) != _hash(target) or macro_path.read_bytes() != macro_bytes:
        raise RuntimeError("Windows compatibility file verification failed")
    configuration = {"MUJOCO_GPU_RENDERING": False, "FILE_LOGGING_LEVEL": None,
                     "render_backend": "glfw", "macro_mechanism": "official_private_hook_sets_actual_module_fields"}
    record = {"schema_version": "remaining-libero-windows-compat-v1", "platform": "Windows",
              "package_versions": {name: dist.version for name, dist in distributions.items()},
              "configuration": configuration,
              "source_dll": {"path": str(source), "sha256": _hash(source)},
              "target_dll": {"path": str(target), "sha256": _hash(target)},
              "macro_file": {"path": str(macro_path), "sha256": _hash(macro_path)},
              "preparation_source_sha256": _hash(Path(__file__)),
              "upstream_python_files_modified": False}
    (runtime / "windows_compat.json").write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    return record


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args(argv)
    print(json.dumps(prepare_windows(), indent=2), flush=True)


if __name__ == "__main__":
    main()
